# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_Name', models.CharField(max_length=255, unique=True)),
                ('field', models.CharField(max_length=255, null=True)),
                ('size', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('pub_datetime', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobslist.Employer')),
            ],
        ),
    ]
