# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist', '0005_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='contact',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
