# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist', '0007_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='employer',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
