# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist', '0008_auto_20160706_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='picture',
        ),
    ]
